### ISSUE TITLE
Communicate to Solr over HTTPS

### ISSUE THREAD

**Issue by bratislav** [toastdriven/pysolr#163]
Hi,

I'm trying to communicate to Solr via HTTPS (SSL) but it isn't working. I have changed scheme in SOLR_URL param in my Django app to https and now when I fire search request I'm getting

Failed to connect to server https://127.0.0.1:8983/...help: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

Can I disable verification somehow or do I need to import pem (or some other) file somewhere on my server?

Any help much appreciated.

**Comment by acdha** [comment]
This doesn't appear to be specific to pysolr – since it uses requests, your ability to connect over HTTPS will be the same as other requests based clients – see:

http://docs.python-requests.org/en/latest/user/advanced/#ssl-cert-verification

If you needed to use a custom CA you could either use the `REQUESTS_CA_BUNDLE` environmental variable as documented or set `verify` on the pysolr `.session` attribute to the path of a file containing your custom CA.
