### ISSUE TITLE
Get access to solr url

### ISSUE THREAD

**Issue by haveaguess** [toastdriven/pysolr#178]
Sometimes it's useful to get access to the raw solr url to debug things, perhaps you could consider exposing it somehow?

**Comment by haveaguess** [comment]
obviously assuming HTTP GET was used when:
        if len(params_encoded) < 1024:

**Comment by acdha** [comment]
I'm assuming you mean the URL used for queries rather than `Solr.url`, correct?

If you're just using it for debugging, configure logging to have the `pysolr` logger at level debug and you should see the full URL and portions of the request body:

https://github.com/toastdriven/pysolr/blob/master/pysolr.py#L353-L354

**Comment by haveaguess** [comment]
Thanks for reply! 

We exposed the URL programmatically to our advanced users to debug with in our front-end when we used low level request.

I'll see if there is something I can pull request back to you

**Comment by acdha** [comment]
Ah, that makes sense. I'd be tempted to suggest subclassing Solr and having a `_select` method stashes the values somewhere so you don't have to special case the GET / POST branches based on the query size.
